PRODUCT_COPY_FILES += \
    vendor/sony/shinano-common/proprietary/system/etc/firmware/a330_pfp.fw:system/etc/firmware/a330_pfp.fw \
    vendor/sony/shinano-common/proprietary/system/etc/firmware/a330_pm4.fw:system/etc/firmware/a330_pm4.fw \
    vendor/sony/shinano-common/proprietary/system/etc/firmware/cmnlib.b00:system/etc/firmware/cmnlib.b00 \
    vendor/sony/shinano-common/proprietary/system/etc/firmware/cmnlib.b01:system/etc/firmware/cmnlib.b01 \
    vendor/sony/shinano-common/proprietary/system/etc/firmware/cmnlib.b02:system/etc/firmware/cmnlib.b02 \
    vendor/sony/shinano-common/proprietary/system/etc/firmware/cmnlib.b03:system/etc/firmware/cmnlib.b03 \
    vendor/sony/shinano-common/proprietary/system/etc/firmware/cmnlib.mdt:system/etc/firmware/cmnlib.mdt \
    vendor/sony/shinano-common/proprietary/system/etc/firmware/cpp_firmware_v1_2_0.fw:system/etc/firmware/cpp_firmware_v1_2_0.fw \
    vendor/sony/shinano-common/proprietary/system/etc/firmware/tzhdcp.b00:system/etc/firmware/tzhdcp.b00 \
    vendor/sony/shinano-common/proprietary/system/etc/firmware/tzhdcp.b01:system/etc/firmware/tzhdcp.b01 \
    vendor/sony/shinano-common/proprietary/system/etc/firmware/tzhdcp.b02:system/etc/firmware/tzhdcp.b02 \
    vendor/sony/shinano-common/proprietary/system/etc/firmware/tzhdcp.b03:system/etc/firmware/tzhdcp.b03 \
    vendor/sony/shinano-common/proprietary/system/etc/firmware/tzhdcp.mdt:system/etc/firmware/tzhdcp.mdt \
    vendor/sony/shinano-common/proprietary/system/etc/firmware/tzlibasb.b00:system/etc/firmware/tzlibasb.b00 \
    vendor/sony/shinano-common/proprietary/system/etc/firmware/tzlibasb.b01:system/etc/firmware/tzlibasb.b01 \
    vendor/sony/shinano-common/proprietary/system/etc/firmware/tzlibasb.b02:system/etc/firmware/tzlibasb.b02 \
    vendor/sony/shinano-common/proprietary/system/etc/firmware/tzlibasb.b03:system/etc/firmware/tzlibasb.b03 \
    vendor/sony/shinano-common/proprietary/system/etc/firmware/tzlibasb.mdt:system/etc/firmware/tzlibasb.mdt \
    vendor/sony/shinano-common/proprietary/system/etc/firmware/tznautilus.b00:system/etc/firmware/tznautilus.b00 \
    vendor/sony/shinano-common/proprietary/system/etc/firmware/tznautilus.b01:system/etc/firmware/tznautilus.b01 \
    vendor/sony/shinano-common/proprietary/system/etc/firmware/tznautilus.b02:system/etc/firmware/tznautilus.b02 \
    vendor/sony/shinano-common/proprietary/system/etc/firmware/tznautilus.b03:system/etc/firmware/tznautilus.b03 \
    vendor/sony/shinano-common/proprietary/system/etc/firmware/tznautilus.mdt:system/etc/firmware/tznautilus.mdt \
    vendor/sony/shinano-common/proprietary/system/etc/firmware/tzsuntory.b00:system/etc/firmware/tzsuntory.b00 \
    vendor/sony/shinano-common/proprietary/system/etc/firmware/tzsuntory.b01:system/etc/firmware/tzsuntory.b01 \
    vendor/sony/shinano-common/proprietary/system/etc/firmware/tzsuntory.b02:system/etc/firmware/tzsuntory.b02 \
    vendor/sony/shinano-common/proprietary/system/etc/firmware/tzsuntory.b03:system/etc/firmware/tzsuntory.b03 \
    vendor/sony/shinano-common/proprietary/system/etc/firmware/tzsuntory.mdt:system/etc/firmware/tzsuntory.mdt \
    vendor/sony/shinano-common/proprietary/system/etc/firmware/tzwidevine.b00:system/etc/firmware/tzwidevine.b00 \
    vendor/sony/shinano-common/proprietary/system/etc/firmware/tzwidevine.b01:system/etc/firmware/tzwidevine.b01 \
    vendor/sony/shinano-common/proprietary/system/etc/firmware/tzwidevine.b02:system/etc/firmware/tzwidevine.b02 \
    vendor/sony/shinano-common/proprietary/system/etc/firmware/tzwidevine.b03:system/etc/firmware/tzwidevine.b03 \
    vendor/sony/shinano-common/proprietary/system/etc/firmware/tzwidevine.mdt:system/etc/firmware/tzwidevine.mdt \
    vendor/sony/shinano-common/proprietary/system/etc/firmware/venus.b00:system/etc/firmware/venus.b00 \
    vendor/sony/shinano-common/proprietary/system/etc/firmware/venus.b01:system/etc/firmware/venus.b01 \
    vendor/sony/shinano-common/proprietary/system/etc/firmware/venus.b02:system/etc/firmware/venus.b02 \
    vendor/sony/shinano-common/proprietary/system/etc/firmware/venus.b03:system/etc/firmware/venus.b03 \
    vendor/sony/shinano-common/proprietary/system/etc/firmware/venus.b04:system/etc/firmware/venus.b04 \
    vendor/sony/shinano-common/proprietary/system/etc/firmware/venus.mbn:system/etc/firmware/venus.mbn \
    vendor/sony/shinano-common/proprietary/system/etc/firmware/venus.mdt:system/etc/firmware/venus.mdt \
    vendor/sony/shinano-common/proprietary/system/vendor/firmware/keymaster/keymaster.b00:system/vendor/firmware/keymaster/keymaster.b00 \
    vendor/sony/shinano-common/proprietary/system/vendor/firmware/keymaster/keymaster.b01:system/vendor/firmware/keymaster/keymaster.b01 \
    vendor/sony/shinano-common/proprietary/system/vendor/firmware/keymaster/keymaster.b02:system/vendor/firmware/keymaster/keymaster.b02 \
    vendor/sony/shinano-common/proprietary/system/vendor/firmware/keymaster/keymaster.b03:system/vendor/firmware/keymaster/keymaster.b03 \
    vendor/sony/shinano-common/proprietary/system/vendor/firmware/keymaster/keymaster.mdt:system/vendor/firmware/keymaster/keymaster.mdt \
    vendor/sony/shinano-common/proprietary/system/vendor/firmware/libpn547_fw.so:system/vendor/firmware/libpn547_fw.so \

