PRODUCT_COPY_FILES += \
    vendor/sony/shinano-common/proprietary/etc/firmware/a330_pfp.fw:etc/firmware/a330_pfp.fw \
    vendor/sony/shinano-common/proprietary/etc/firmware/a330_pm4.fw:etc/firmware/a330_pm4.fw \
    vendor/sony/shinano-common/proprietary/etc/firmware/cmnlib.b00:etc/firmware/cmnlib.b00 \
    vendor/sony/shinano-common/proprietary/etc/firmware/cmnlib.b01:etc/firmware/cmnlib.b01 \
    vendor/sony/shinano-common/proprietary/etc/firmware/cmnlib.b02:etc/firmware/cmnlib.b02 \
    vendor/sony/shinano-common/proprietary/etc/firmware/cmnlib.b03:etc/firmware/cmnlib.b03 \
    vendor/sony/shinano-common/proprietary/etc/firmware/cmnlib.mdt:etc/firmware/cmnlib.mdt \
    vendor/sony/shinano-common/proprietary/etc/firmware/cpp_firmware_v1_2_0.fw:etc/firmware/cpp_firmware_v1_2_0.fw \
    vendor/sony/shinano-common/proprietary/etc/firmware/tzhdcp.b00:etc/firmware/tzhdcp.b00 \
    vendor/sony/shinano-common/proprietary/etc/firmware/tzhdcp.b01:etc/firmware/tzhdcp.b01 \
    vendor/sony/shinano-common/proprietary/etc/firmware/tzhdcp.b02:etc/firmware/tzhdcp.b02 \
    vendor/sony/shinano-common/proprietary/etc/firmware/tzhdcp.b03:etc/firmware/tzhdcp.b03 \
    vendor/sony/shinano-common/proprietary/etc/firmware/tzhdcp.mdt:etc/firmware/tzhdcp.mdt \
    vendor/sony/shinano-common/proprietary/etc/firmware/tzlibasb.b00:etc/firmware/tzlibasb.b00 \
    vendor/sony/shinano-common/proprietary/etc/firmware/tzlibasb.b01:etc/firmware/tzlibasb.b01 \
    vendor/sony/shinano-common/proprietary/etc/firmware/tzlibasb.b02:etc/firmware/tzlibasb.b02 \
    vendor/sony/shinano-common/proprietary/etc/firmware/tzlibasb.b03:etc/firmware/tzlibasb.b03 \
    vendor/sony/shinano-common/proprietary/etc/firmware/tzlibasb.mdt:etc/firmware/tzlibasb.mdt \
    vendor/sony/shinano-common/proprietary/etc/firmware/tznautilus.b00:etc/firmware/tznautilus.b00 \
    vendor/sony/shinano-common/proprietary/etc/firmware/tznautilus.b01:etc/firmware/tznautilus.b01 \
    vendor/sony/shinano-common/proprietary/etc/firmware/tznautilus.b02:etc/firmware/tznautilus.b02 \
    vendor/sony/shinano-common/proprietary/etc/firmware/tznautilus.b03:etc/firmware/tznautilus.b03 \
    vendor/sony/shinano-common/proprietary/etc/firmware/tznautilus.mdt:etc/firmware/tznautilus.mdt \
    vendor/sony/shinano-common/proprietary/etc/firmware/tzsuntory.b00:etc/firmware/tzsuntory.b00 \
    vendor/sony/shinano-common/proprietary/etc/firmware/tzsuntory.b01:etc/firmware/tzsuntory.b01 \
    vendor/sony/shinano-common/proprietary/etc/firmware/tzsuntory.b02:etc/firmware/tzsuntory.b02 \
    vendor/sony/shinano-common/proprietary/etc/firmware/tzsuntory.b03:etc/firmware/tzsuntory.b03 \
    vendor/sony/shinano-common/proprietary/etc/firmware/tzsuntory.mdt:etc/firmware/tzsuntory.mdt \
    vendor/sony/shinano-common/proprietary/etc/firmware/tzwidevine.b00:etc/firmware/tzwidevine.b00 \
    vendor/sony/shinano-common/proprietary/etc/firmware/tzwidevine.b01:etc/firmware/tzwidevine.b01 \
    vendor/sony/shinano-common/proprietary/etc/firmware/tzwidevine.b02:etc/firmware/tzwidevine.b02 \
    vendor/sony/shinano-common/proprietary/etc/firmware/tzwidevine.b03:etc/firmware/tzwidevine.b03 \
    vendor/sony/shinano-common/proprietary/etc/firmware/tzwidevine.mdt:etc/firmware/tzwidevine.mdt \
    vendor/sony/shinano-common/proprietary/etc/firmware/venus.b00:etc/firmware/venus.b00 \
    vendor/sony/shinano-common/proprietary/etc/firmware/venus.b01:etc/firmware/venus.b01 \
    vendor/sony/shinano-common/proprietary/etc/firmware/venus.b02:etc/firmware/venus.b02 \
    vendor/sony/shinano-common/proprietary/etc/firmware/venus.b03:etc/firmware/venus.b03 \
    vendor/sony/shinano-common/proprietary/etc/firmware/venus.b04:etc/firmware/venus.b04 \
    vendor/sony/shinano-common/proprietary/etc/firmware/venus.mbn:etc/firmware/venus.mbn \
    vendor/sony/shinano-common/proprietary/etc/firmware/venus.mdt:etc/firmware/venus.mdt \
    vendor/sony/shinano-common/proprietary/vendor/firmware/keymaster/keymaster.b00:vendor/firmware/keymaster/keymaster.b00 \
    vendor/sony/shinano-common/proprietary/vendor/firmware/keymaster/keymaster.b01:vendor/firmware/keymaster/keymaster.b01 \
    vendor/sony/shinano-common/proprietary/vendor/firmware/keymaster/keymaster.b02:vendor/firmware/keymaster/keymaster.b02 \
    vendor/sony/shinano-common/proprietary/vendor/firmware/keymaster/keymaster.b03:vendor/firmware/keymaster/keymaster.b03 \
    vendor/sony/shinano-common/proprietary/vendor/firmware/keymaster/keymaster.mdt:vendor/firmware/keymaster/keymaster.mdt \
    vendor/sony/shinano-common/proprietary/vendor/firmware/libpn547_fw.so:vendor/firmware/libpn547_fw.so \

